.github/workflows/build.yml
package.json
src/container/ContainerBase/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/OtherContainer/PriorityQueue.ts
src/container/OtherContainer/Queue.ts
src/container/OtherContainer/Stack.ts
src/container/SequentialContainer/Base/index.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeBaseContainer.ts
src/container/TreeContainer/Base/TreeNode.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
src/utils/checkParams.ts

docs: update documentation

---

CHANGELOG.md
src/container/ContainerBase/index.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeBaseContainer.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
test/OtherTest/iterator.test.ts
test/SequentialContainerTest/LinkList.test.ts

perf: improve iterator

---

.github/workflows/build.yml
package.json
src/container/ContainerBase/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/OtherContainer/PriorityQueue.ts
src/container/OtherContainer/Queue.ts
src/container/OtherContainer/Stack.ts
src/container/SequentialContainer/Base/index.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeBaseContainer.ts
src/container/TreeContainer/Base/TreeNode.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
src/utils/checkParams.ts

docs: update documetation

---

CHANGELOG.md
src/container/ContainerBase/index.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeBaseContainer.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
test/HashContainerTest/HashMap.test.ts
test/HashContainerTest/HashSet.test.ts
test/OtherTest/iterator.test.ts
test/TreeContainerTest/OrderedMap.test.ts
test/TreeContainerTest/OrderedSet.test.ts

feat: add insert and update function by iterator hint

---

.github/FUNDING.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml
.github/workflows/test.yml

ci: update workflow

---

src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
test/HashContainerTest/HashMap.test.ts
test/HashContainerTest/HashSet.test.ts

test: make hashcontainer tests stronger

---

CHANGELOG.md

docs: fix wrong title

---

src/container/OtherContainer/PriorityQueue.ts
test/OtherContainerTest/PriorityQueue.test.ts
test/OtherTest/iterator.test.ts

perf: improve heap

---

gulpfile.ts
package.json
yarn.lock

I checked and fixed the typescript transformer settings in the rollup.
As a result, the umd build size decreased by 3KB to 37KB.

fix: add missing transform to rollup build

---

CHANGELOG.md

I wrote a changelog for #24 PR.

docs: update changelog for #24

---

CHANGELOG.md
README.md
README.zh-CN.md

docs: do some update

---

gulpfile.ts
package.json
src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/OtherContainer/PriorityQueue.ts
src/container/OtherContainer/Queue.ts
src/container/OtherContainer/Stack.ts
src/container/SequentialContainer/Base/RandomIterator.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
src/utils/checkParams.macro.ts
test/HashContainerTest/HashMap.test.ts
test/HashContainerTest/HashSet.test.ts
tsconfig.json
yarn.lock

All exported members are not expected to be inherited so `protected/private` name can be converted to improve performance and reduce packing size.

refactor: add _ perfix for private and protected member

---

src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/OtherContainer/Queue.ts
src/container/SequentialContainer/Base/RandomIterator.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts

perf: do some perf

---

CHANGELOG.md
package.json

Update to version 4.1.5-beta.0.

build: publish@4.1.5-beta.0 [dev]

---

CHANGELOG.md
src/container/TreeContainer/Base/TreeIterator.ts
test/TreeContainerTest/OrderedSet.test.ts

fix: get wrong tree index when size is 0

---

CHANGELOG.md
package.json

Update to version 4.1.5-beta.0.

build: publish@4.1.5 beta.1 [dev]

---

CHANGELOG.md
src/container/OtherContainer/PriorityQueue.ts
test/OtherContainerTest/PriorityQueue.test.ts

See https://github.com/js-sdsl/js-sdsl/issues/51.

feat: make heap stronger

---

package.json
src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/OtherContainer/PriorityQueue.ts
src/container/SequentialContainer/Base/RandomIterator.ts
src/container/SequentialContainer/LinkList.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/Base/TreeNode.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
yarn.lock

docs: update typo

---

.github/workflows/build.yml
tools/publishIsolate.ts

build: publish isolate

---

README.md
README.zh-CN.md

in the course of documentation Readme also seems to need to be updated

docs: add isolate packages info to readme

---

gulpfile.ts
tools/buildFactory.ts

chore: add sourcemap for ts

---

.github/workflows/deploy-preview.yml
src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/OtherContainer/PriorityQueue.ts
src/container/SequentialContainer/Base/index.ts
src/container/SequentialContainer/LinkList.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/Base/TreeNode.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts

docs: add examples for api in typedoc

---

.github/workflows/deploy-preview.yml

ci: add deploy preview permission

---

CHANGELOG.md
README.md
README.zh-CN.md

docs: update readme and changelog [skip ci]

---

.github/workflows/compressed-size.yml
.github/workflows/deploy-preview.yml
package.json

ci: add compress size action

---

.github/workflows/compressed-size.yml
.github/workflows/deploy-preview.yml
.github/workflows/test.yml

ci: optimize workflow

---

.github/workflows/compressed-size.yml
.github/workflows/deploy-preview.yml

ci: fix failed ci

---

.github/workflows/compressed-size.yml
.github/workflows/deploy-preview.yml

ci: fix failed workflow

---

src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts

refactor: change iterator export to export type

---

.gitpod.yml
README.md
README.zh-CN.md

docs: update readme

---

CHANGELOG.md
karma.conf.ts
src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
test/OtherTest/symbol-iterator.test.ts
yarn.lock

feat: add `this` param for `forEach` function

---

.github/workflows/build.yml
.github/workflows/deploy-preview.yml

ci: fix wrong config for deploy

---

README.md
README.zh-CN.md

docs: improve readme

---

README.md
README.zh-CN.md

docs: update previous docs hint

---

.github/workflows/deploy-preview.yml

ci: fix deploy workflow

---

.github/workflows/deploy-preview.yml

ci: fix pr preview error

---

.github/workflows/build.yml
karma.conf.ts
package.json
tsconfig.json

chore: make test exclude from tsconfig

---

karma.conf.ts
performance/HashContainerTest/HashMap.performance.ts
performance/HashContainerTest/HashSet.performance.ts
performance/index.ts
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/TreeContainer/Base/TreeNode.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/utils/checkNotObject.ts
test/HashContainerTest/HashMap.test.ts
test/HashContainerTest/HashSet.test.ts
test/utils/generateRandom.ts

refactor: change hash container implement method

---

.github/workflows/compressed-size.yml
.github/workflows/test.yml

ci: fix wrong trigger paths

---

performance/TreeContainerTest/OrderedMap.performance.ts
performance/TreeContainerTest/OrderedSet.performance.ts
src/container/OtherContainer/PriorityQueue.ts
src/container/OtherContainer/Stack.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts

perf: remove all the arrow function

---

src/container/HashContainer/Base/index.ts

perf: set obj property to null

---

CHANGELOG.md
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/Base/TreeNode.ts

perf: remove useless tree node class member

---

.github/workflows/codeql-analysis.yml
CHANGELOG.md
src/container/ContainerBase/index.ts
src/container/OtherContainer/PriorityQueue.ts
src/container/OtherContainer/Queue.ts
src/container/OtherContainer/Stack.ts
src/container/SequentialContainer/Base/RandomIterator.ts
src/container/SequentialContainer/Base/index.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
src/utils/checkParams.macro.ts
src/utils/throwError.ts
test/OtherTest/constructor.test.ts
test/OtherTest/iterator.test.ts
test/SequentialContainerTest/Deque.test.ts
test/SequentialContainerTest/LinkList.test.ts
test/SequentialContainerTest/SequentialContainer.test.ts
test/TreeContainerTest/OrderedMap.test.ts
test/TreeContainerTest/OrderedSet.test.ts

feat: do some optimization

---

CHANGELOG.md
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/index.ts
test/HashContainerTest/HashMap.test.ts
test/HashContainerTest/HashSet.test.ts
test/OtherTest/iterator.test.ts
test/OtherTest/symbol-iterator.test.ts
test/utils/generateRandom.ts
yarn.lock

feat: make hash container linked

---

CHANGELOG.md
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
test/TreeContainerTest/OrderedMap.test.ts
test/TreeContainerTest/OrderedSet.test.ts

fix: tree erase reverse iterator return wrong iter

---

CHANGELOG.md
src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/SequentialContainer/Base/RandomIterator.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/OrderedMap.ts
test/OtherContainerTest/PriorityQueue.test.ts
test/OtherContainerTest/Queue.test.ts
test/OtherContainerTest/Stack.test.ts
test/SequentialContainerTest/Deque.test.ts
test/SequentialContainerTest/LinkList.test.ts
test/SequentialContainerTest/SequentialContainer.test.ts
test/utils/judge.ts
yarn.lock

refactor: do some refactor

---

CHANGELOG.md
package.json
src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/OtherContainer/PriorityQueue.ts
src/container/OtherContainer/Queue.ts
src/container/OtherContainer/Stack.ts
src/container/SequentialContainer/Base/RandomIterator.ts
src/container/SequentialContainer/Base/index.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/Base/TreeNode.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
src/utils/checkObject.ts
src/utils/checkParams.macro.ts
src/utils/throwError.ts
test/HashContainerTest/HashMap.test.ts
test/HashContainerTest/HashSet.test.ts
test/SequentialContainerTest/Deque.test.ts
test/SequentialContainerTest/LinkList.test.ts
test/SequentialContainerTest/SequentialContainer.test.ts
test/TreeContainerTest/OrderedMap.test.ts
test/TreeContainerTest/OrderedSet.test.ts
yarn.lock

feat: add return value to all `insert` liked function

---

CHANGELOG.md
README.zh-CN.md
src/container/ContainerBase/index.ts
src/container/OtherContainer/Queue.ts
src/container/SequentialContainer/Deque.ts
src/utils/getContainerSize.macro.ts
test/IsolationTest/index.ts
test/OtherContainerTest/Queue.test.ts
test/SequentialContainerTest/Deque.test.ts
yarn.lock

reafactor: reimplement `Queue`, separate `Queue` from `Deque`

---

src/container/HashContainer/HashMap.ts

docs: move comment to right place

---

src/container/OtherContainer/Queue.ts

perf: optimize the expansion mechanism of queue

---

src/container/HashContainer/Base/index.ts
src/container/SequentialContainer/Deque.ts
src/container/TreeContainer/Base/TreeNode.ts

perf: do some judgement

---

CHANGELOG.md
README.md
README.zh-CN.md
conf/isolate.config.json
package.json
src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/OtherContainer/Queue.ts
src/container/SequentialContainer/Base/RandomIterator.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/Base/TreeNode.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
src/utils/getContainerSize.macro.ts
test/IsolationTest/index.ts
test/OtherContainerTest/Queue.test.ts
test/OtherTest/iterator.test.ts
test/SequentialContainerTest/Deque.test.ts
yarn.lock

Publish version 4.3.0.
Expected to be released at 01.20.
**note: The last commit must be build: publish@{version}.**

build: publish@4.3.0

---

CHANGELOG.md
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/HashContainer/HashSet.ts
src/container/SequentialContainer/Base/index.ts
src/container/SequentialContainer/Deque.ts
src/container/SequentialContainer/LinkList.ts
src/container/SequentialContainer/Vector.ts
src/container/TreeContainer/Base/index.ts
src/container/TreeContainer/OrderedMap.ts
src/container/TreeContainer/OrderedSet.ts
src/utils/math.ts
test/SequentialContainerTest/Deque.test.ts
yarn.lock

perf: optimized many places

---

CHANGELOG.md
conf/isolate.config.json
package.json

build: publish@4.4.0 [dev]

---

CHANGELOG.md
conf/isolate.config.json
package.json

build: publish@4.4.1 [dev]

---

src/container/HashContainer/HashMap.ts
src/container/TreeContainer/OrderedMap.ts
test/HashContainerTest/HashMap.test.ts
test/TreeContainerTest/OrderedMap.test.ts
yarn.lock

fix: make iterator pointer proxy iterable

---

src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/SequentialContainer/Base/RandomIterator.ts
src/container/SequentialContainer/LinkList.ts
src/container/TreeContainer/Base/TreeIterator.ts
test/OtherTest/iterator.test.ts

feat: add isAccessible func to iter

---

CHANGELOG.md
conf/isolate.config.json
package.json
src/container/ContainerBase/index.ts
src/container/HashContainer/Base/index.ts
src/container/HashContainer/HashMap.ts
src/container/SequentialContainer/Base/RandomIterator.ts
src/container/SequentialContainer/LinkList.ts
src/container/TreeContainer/Base/TreeIterator.ts
src/container/TreeContainer/OrderedMap.ts
test/HashContainerTest/HashMap.test.ts
test/OtherTest/iterator.test.ts
test/TreeContainerTest/OrderedMap.test.ts
yarn.lock

Publish version 4.4.2.
Expected to be released at 07.21.
note: The last commit must be build: publish@{version}.

build: publish@4.4.2

---

README.md

docs: fix typos and improve grammar in readme
